import { Open_Sans } from "next/font/google";
import "./styles/globals.css";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { UserProvider } from "@/context/UserContext";
import { CartProvider } from "@/context/CartContext";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} antialiased`}
        suppressHydrationWarning
      >
        <CartProvider>
          <UserProvider>{children}</UserProvider>
        </CartProvider>
      </body>
    </html>
  );
}
